- id: doi:10.1038/s41588-021-00935-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-021-00935-7/MediaObjects/41588_2021_935_Fig1_HTML.png
  date: 2021-10-5
  extra-links:
    - type: source code
      text: A large multi-ancestry HLA imputation reference panel that helps identifying causal disease variations.
      link: https://github.com/yang-luo-lab/HLA-TAPAS


- id: doi:10.1093/hmg/ddab130
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8330913/bin/ddab130f1.jpg
  date: 2021-08-15
  extra-links:
    - type: source code
      link: https://github.com/yang-luo-lab/cov-ldsc
      text: A method to provide robust hg2 estimates from GWAS summary statistics and in-sample LD estimates in admixed populations.
