
# HLA-TCR
- id: doi:10.1126/sciadv.adu3461
  image: images/HLA-TCR.png
  extra-links:
    - type: data
      link: https://github.com/yang-luo-lab/TCR-HLA
      text: Reproducing results from manuscript

# COMBAT eQTL
- id: doi:10.1101/2025.06.30.25330463
  image: images/combat-eQTL.png

# smoking review
- id: doi:10.1038/d41586-024-00232-3
  image: images/smoke_review.png

# TB genome-to-genome
- id: pmid:39613754
  image: images/g2g_overview.svg
  extra-links:
    - type: data
      link: https://github.com/yang-luo-lab/TB-g2g
      text: Reproducing results from manuscript

#eBL
- id: doi:10.1038/s42003-023-05701-5
  image: images/eBL_HLA.png

# scHLApers
- id: doi:10.1038/s41588-023-01586-6
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-023-01586-6/MediaObjects/41588_2023_1586_Fig1_HTML.png?as=webp


# hla tapas
- id: doi:10.1038/s41588-021-00935-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-021-00935-7/MediaObjects/41588_2021_935_Fig1_HTML.png
  extra-links:
    - type: source
      text: source code
      link: https://github.com/yang-luo-lab/HLA-TAPAS

# HLA-CD4 TCR
- id: doi:10.1038/s41588-022-01032-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-022-01032-z/MediaObjects/41588_2022_1032_Fig1_HTML.png?as=webp

# peruvian height
- id: doi:10.1038/s41586-020-2302-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2302-0/MediaObjects/41586_2020_2302_Fig1_HTML.png?as=webp

# covldsc
- id: pmc:PMC8330913
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8330913/bin/ddab130f1.jpg
  extra-links:
    - type: source
      link: https://github.com/yang-luo-lab/cov-ldsc
      text: Source code for running cov-LDSC


# Peruvian TB GWAS
- id: doi:10.1038/s41467-019-11664-1
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=493290&s=91&r=2&c=2
  extra-links:
    - type: data
      text: Summary statistics
      link: https://www.ebi.ac.uk/gwas/downloads/summary-statistics
    - type: source
      text: Reproducing results from manuscript
      link: https://github.com/yang-luo-lab/TB_progression_GWAS