
#eBL
- id: doi:10.1038/s42003-023-05701-5
  date: 2024-01-5
  
# scHLApers
- id: doi:10.1038/s41588-023-01586-6
  date: 2023-11-3
  image: https://github.com/immunogenomics/scHLApers/blob/main/images/overview.png

#westAfricaHLA
- id:doi.org/10.1371/journal.pone.0291437
  date: 2023-9-28
  image: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0291437

# hla
- id: doi:10.1038/s41588-021-00935-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-021-00935-7/MediaObjects/41588_2021_935_Fig1_HTML.png
  date: 2021-10-5
  extra-links:
    - type: source
      text: source code
      link: https://github.com/yang-luo-lab/HLA-TAPAS

# covldsc
- id: pmc:PMC8330913
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8330913/bin/ddab130f1.jpg
  extra-links:
    - type: source
      link: https://github.com/yang-luo-lab/cov-ldsc
      text: Source code

# flot1
- id: doi:10.1101/2022.02.07.22270622
  image: images/g2g_overview.svg
  #date:2022-02-08
  extra-links:s
    - type: data
      link: https://github.com/yang-luo-lab/TB-g2g
      text: Reproducing results from manuscript

# Peruvian TB GWAS
- id: doi:10.1038/s41467-019-11664-1
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=493290&s=91&r=2&c=2
  #date:2019-08-21
  extra-links:
    - type: data
      text: Summary statistics
      link: https://www.ebi.ac.uk/gwas/downloads/summary-statistics
    - type: source
      text: Reproducing results from manuscript
      link: https://github.com/yang-luo-lab/TB_progression_GWAS